name: node.yml
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  npm-build-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Change directory
        run: cd frontend/

      - name: Installing Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Installing dependencies
        run: npm ci

      - name: Start dev server
        run: npm run dev & sleep 10



